apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: gauravsinghphippyandfriends 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gauravsinghphippyandfriends 
    spec:
      containers:
        - name: gauravsinghphippyandfriends 
          image: sydneyacr.azurecr.io/gauravsinghphippyandfriends
          ports:
          - containerPort: 80